apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-oly
spec:
  template:
    metadata:
      name: pod-my-nginx
      labels:
        env: dev
    spec:
      containers:
      - name: nginx-container
        image: nginx
  selector:
    matchLabels:
      env: dev
  replicas: 4
