apiVersion: v1
kind: Pod

metadata:
  name: tomcat-pod
  labels:
    name: app-java

spec:
  containers:
  - name: container-tomcat
    image: tomcat:latest
  imagePullSecrets:
  - name: my-registry-secret